# Generated by Django 3.0.8 on 2020-07-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
